default_language_version:
    python: python3.12

repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.24.1
    hooks:
      - id: typos
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      -   id: pip-audit
          args: ["--vulnerability-service", "osv", "--cache-dir", ".pip_audit_cache"]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black app
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: isort app
        language: python
        types: [python]
      - id: ruff
        name: ruff
        entry: ruff check app
        language: python
        types: [python]
