version: "3.9"

services:
  db:
    image: postgres:16
    container_name: {{cookiecutter.project_name}}-database
    restart: always
    volumes:
      - {{cookiecutter.project_name}}-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: {{cookiecutter.project_name}}
      POSTGRES_USER: {{cookiecutter.project_name}}
      POSTGRES_DB: {{cookiecutter.project_name}}
    ports:
      - "5432:5432"

  django:
    build:
      context: .
    restart: always
    volumes:
      - ./app:/app
      - ./static:/static
    depends_on:
      - db
    working_dir: /app
    command: [ "/wait-for-it.sh", "db:5432", "--", "../start-dev.sh" ]
    ports:
      - "8000:8000"

  # Email testing
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: {{ cookiecutter.project_name }}-mailhog
    volumes:
      - ./docker-maildir:/maildir
    command: [ "-storage=maildir", "-maildir-path=/maildir" ]
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
    {{cookiecutter.project_name}}-postgresql:
