name: "Large PR checker"
description: "Blocks PR if number of lines changed is excessive. Modified version of https://github.com/adolfosilva/gh-large-pr-check/blob/main/action.yml"

inputs:
  max_lines_changed:
    description: "Maximum number of lines changed allowed"
    required: true
    default: "500"
  target_branch:
    description: The branch to compare against
    required: true
    default: main
outputs:
  total_lines_changed:
    description: "Total lines changed in this PR"
    value: ${{ steps.get_total_lines_changed.outputs.total_lines_changed }}

runs:
  using: "composite"
  steps:
    - id: fetch_target_branch
      run: |
        git fetch origin ${{ inputs.target_branch }}
      shell: bash
    - id: get_total_lines_changed
      run: |
        size=$(git diff --shortstat origin/${{ inputs.target_branch }} ':(exclude)*.lock' \
        | awk '{ print $4+$6 }' \
        | awk -F- '{print $NF}' \
        | bc)

        echo ""
        echo "Total lines changed (note: *.lock files are excluded from this count): $size"
        echo "total_lines_changed=$size" >> $GITHUB_OUTPUT
      shell: bash
    - name: Comment PR
      if: ${{ fromJSON(steps.get_total_lines_changed.outputs.total_lines_changed) > fromJSON(inputs.max_lines_changed) }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: pr_size
        mode: recreate
        message: |
          :boom: :boom: :boom:
          Total lines changed ${{ steps.get_total_lines_changed.outputs.total_lines_changed }} is greater than ${{ inputs.max_lines_changed }}.
          Please consider breaking this PR down.
    - id: fail
      if: ${{ fromJSON(steps.get_total_lines_changed.outputs.total_lines_changed) > fromJSON(inputs.max_lines_changed) }}
      run: exit 1
      shell: bash
